travis:
  secure:
    BINSTAR_TOKEN: 63lJx+MsM+Vy9PGPpcF06iMrgct65VEMxjNnlVHWdkPZKMuTkE1LtGA9feC9ao5ANsjdKqYvEtgpfEV7fV3PAeF516da3ptJ1OZFd0UKjWR95r8Gkyl24CYsYAKysFGTXb5yJZNFpm/kRrHc4l6/BrPyXRuz7BQYsjlyje6ebp3JmnZFhCPzb4gCGcTPeBWsD+LQNZc2xXbrzmA3ONiunTlrAuZ1c1pe31lzsvrf2yeAzopWQKKfsNjVvQdwxcSHpMmVJ0+cPgGtpBHYM6q9wtoX7GzyHu0rryx+OEUZrOPMYvKXgSWgKUF5N6QoQGxPp9qv18JtXcfq0K+wLq3wpnDmJOKoluAlINrkWaZ4Ge2qYKlc824jVCQuMoOVvoAGMZC0KZJqvAz89csRYO6/cq/10TVx8IkvrnjxQfFE5/upL3HRGW2Utkme1/agXEexTnbkMJllLqrQh3jV9kgH4sVf5q5Ok9WuI/XqiI1GoOteQz+9hG9iYqgA3A5wyx/I/IILxBOZp/v4Se0dPy7zFXlDWkObAtSQhdPu73WqHvBD/u4GXt07soJscGJlCjZoIUh0gU9u0nK2SlfQDVaQ9+B+w9XSpA6q48J7abkq4kLNVcVeQCU44dtdX4xKLyk2vXkotvsxOeRhiqkpKFqj1w49zvQ3Hefhek5yjj/cN20=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
